### ISSUE TITLE
Image Support, 'Different Project's Users' Privacy Type, and Video URL

### ISSUE THREAD

**Issue by aevalenzuela** [vanderbilt-redcap/faq-menu-module#1]
Indiana University REDCap is testing/considering FAQ Builder, and we have noticed a few apparent issues:

1. Images don't seem to be supported, whether as favicons, logos, image uploads, etc. I have tried jpegs, png and ico files.

2. The 'Different Project's Users' privacy setting doesn't seem to function correctly. Users on a specified 'different project' are unable to access the FAQ page (via URL).

3. For the Video URL option, FAQ Builder doesn't seem to be adding the iframe code.

Are these elements which just haven't been added/fixed yet, and will be in upcoming releases?

Thanks!

**Comment by knil-maloon** [comment]
Hello,
We got some support to look into it but when checking all the points, it is working for us. We are using REDCap 12.2.7 and PHP 7.3.29 as a testing environment. 

- All images have shown in the config and in the records.
- 'Different Project's Users' privacy setting is detecting the user correctly and displaying as intended.
- The videos are showing but in some instances, like youtube, you have to have the link set up differently to make it work (Something like www.youtube.com/embed/).

If you have more information on to what this is happening let us know as on our regular test everything seemed to be normal.
