### ISSUE TITLE
Bug REDCap 12.x and PHP 8.x

### ISSUE THREAD

**Issue by tvalero** [vanderbilt-redcap/faq-menu-module#2]
When using it with "REDCap 12.0.19 · PHP 8.1.3 (Linux/Unix OS) · MySQL 8.0.28", 

When pushing the PDF button, 
![image](https://user-images.githubusercontent.com/20490491/161576343-f239d5bd-f87e-4a72-882c-00aff88cd7e2.png)

I got an error : 

The URL is http://localhost/redcap_v12.0.19/ExternalModules/?prefix=faq-builder&page=download_PDF&pid=20

Screen copy : 

![image](https://user-images.githubusercontent.com/20490491/161576891-32f651ce-fc0a-4f42-bd63-6fa3a38b82cf.png)

> ( ! )  Fatal error: Uncaught Dompdf\Exception: file_get_contents(): Passing  null to parameter #2 ($use_include_path) of type bool is deprecated 8192  in  /var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php  on line 507
> --
> 
> 
> 
> 1 | 0.0021 | 440432 | {main}(  ) | .../index.php:0
> 2 | 0.7359 | 14484960 | require( '/var/www/html/modules/faq-builder_v1.3/download_PDF.php ) | .../index.php:126
> 3 | 0.9569 | 18069832 | Dompdf\Dompdf->render(  ) | .../download_PDF.php:96
> 4 | 0.9570 | 18086344 | Dompdf\Dompdf->processHtml(  ) | .../Dompdf.php:724
> 5 | 0.9821 | 18352008 | Dompdf\Css\Stylesheet->load_css_file( $file = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/lib/res/html.css', $origin = 1 ) | .../Dompdf.php:572
> 6 | 0.9822 | 18352944 | Dompdf\Helpers::getFileContent( $uri = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/lib/res/html.css', $context = NULL, $offset = ???, $maxlen = ??? ) | .../Stylesheet.php:367
> 7 | 0.9823 | 18353096 | file_get_contents( $filename = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/lib/res/html.css', $use_include_path = NULL, $context = NULL, $offset = 0 ) | .../Helpers.php:839
> 8 | 0.9823 | 18353504 | Dompdf\Helpers::record_warnings( $errno = 8192, $errstr = 'file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated', $errfile = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php', $errline = 839 ) | .../Helpers.php:839
> 
> </font>
> 				<div class="red" style="margin:20px 0px;max-width:700px;">
> 					<b>REDCap crashed due to an unexpected PHP fatal error!</b><br><br>
> 					<b>Error message:</b> Uncaught Dompdf\Exception: 
> file_get_contents(): Passing null to parameter #2 ($use_include_path) of
>  type bool is deprecated 8192 in 
> modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php:507
> Stack trace:
> #0 [internal function]: Dompdf\Helpers::record_warnings(8192, 
> 'file_get_conten...', 'm...', 839)
> #1 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php(839): 
> file_get_contents('m...', NULL, NULL, 0)
> #2 
> modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Css/Stylesheet.php(367):
>  Dompdf\Helpers::getFileContent('m...', NULL)
> #3 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Dompdf.php(572): 
> Dompdf\Css\Stylesheet-&gt;load_css_file('m...', 1)
> #4 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Dompdf.php(724): 
> Dompdf\Dompdf-&gt;processHtml()
> #5 modules/faq-builder_v1.3/download_PDF.php(96): 
> Dompdf\Dompdf-&gt;render()
> #6 redcap_v12.0.19/ExternalModules/index.php(126): require('m...')
> #7 {main}
>   thrown<br>
> 					<b>File:</b> modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php<br>
> 					<b>Line:</b> 507</div>( ! ) Fatal error: Uncaught Dompdf\Exception: [file_get_contents](http://www.php.net/function.file-get-contents)(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated 8192 in /var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php on line 507
> ( ! ) Dompdf\Exception: file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated 8192 in /var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php on line 507
> Call Stack
> #	Time	Memory	Function	Location
> 1	0.0021	440432	{main}( )	.../index.php:0
> 2	0.7359	14484960	require( '/var/www/html/modules/faq-builder_v1.3/download_PDF.php )	.../index.php:126
> 3	0.9569	18069832	Dompdf\Dompdf->render( )	.../download_PDF.php:96
> 4	0.9570	18086344	Dompdf\Dompdf->processHtml( )	.../Dompdf.php:724
> 5	0.9821	18352008	Dompdf\Css\Stylesheet->load_css_file( $file = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/lib/res/html.css', $origin = 1 )	.../Dompdf.php:572
> 6	0.9822	18352944	Dompdf\Helpers::getFileContent( $uri = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/lib/res/html.css', $context = NULL, $offset = ???, $maxlen = ??? )	.../Stylesheet.php:367
> 7	0.9823	18353096	file_get_contents( $filename = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/lib/res/html.css', $use_include_path = NULL, $context = NULL, $offset = 0 )	.../Helpers.php:839
> 8	0.9823	18353504	Dompdf\Helpers::record_warnings( $errno = 8192, $errstr = 'file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated', $errfile = '/var/www/html/modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php', $errline = 839 )	.../Helpers.php:839
> REDCap crashed due to an unexpected PHP fatal error!
> 
> Error message: Uncaught Dompdf\Exception: file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated 8192 in modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php:507 Stack trace: #0 [internal function]: Dompdf\Helpers::record_warnings(8192, 'file_get_conten...', 'm...', 839) #1 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php(839): file_get_contents('m...', NULL, NULL, 0) #2 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Css/Stylesheet.php(367): Dompdf\Helpers::getFileContent('m...', NULL) #3 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Dompdf.php(572): Dompdf\Css\Stylesheet->load_css_file('m...', 1) #4 modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Dompdf.php(724): Dompdf\Dompdf->processHtml() #5 modules/faq-builder_v1.3/download_PDF.php(96): Dompdf\Dompdf->render() #6 redcap_v12.0.19/ExternalModules/index.php(126): require('m...') #7 {main} thrown
> File: modules/faq-builder_v1.3/vendor/dompdf/dompdf/src/Helpers.php
> Line: 507
>

**Comment by tvalero** [comment]
Maybe solved by using a more recent `dompdf` library version.

In `composer.json` :
```json
{
    "require": {
        "dompdf/dompdf": "^1.2"
    }
}
```
instead of : 
```json
 {
     "require": {
        "dompdf/dompdf": "^0.8.3"
     }
 }
```

and launch a `composer upgrade`.

**Comment by knil-maloon** [comment]
Hello,
We were able to look into it but currently REDCap uses PHP 7.3.29 which only allows us to update dompdf to ^0.8.6 version.
